using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AylikMasrafTakibi.scrViews
{
    public partial class scrGiderTanim : Form
    {
        SqlConnection con;
        SqlCommand cmd;
        DataRow dr;
        public scrGiderTanim()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            parGiderTableAdapter1.Fill(dsGider.parGider);
        }
        private void gridView1_InitNewRow(object sender, InitNewRowEventArgs e)
        {
            GridView view = sender as GridView;
            view.SetRowCellValue(e.RowHandle, "pasif", 1);
        }

        private void scrGiderTanim_FormClosing(object sender, FormClosingEventArgs e)
        {
            Application.Exit();
        }

        private void btnKapat_Click(object sender, EventArgs e)
        {
            this.Hide();
            scrMain frm = new scrMain();
            frm.Show();
        }

        private void btnKaydKapat_Click(object sender, EventArgs e)
        {

        }

        private void btnKaydet_Click(object sender, EventArgs e)
        {
            Kaydet();

        }
        private void Kaydet()
        {
            con = new SqlConnection("server=DEVELOPER\\AYSE; Initial Catalog=afb; User ID = sa; Password = 123321 ; Integrated Security=SSPI");
            con.Open();

            DataTable dt = dsGider.Tables[0];
            DataColumn dc = new DataColumn();
            string sqlstr = "";
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                sqlstr = sqlstr + "update parGider set code = '"
                    + dt.Rows[i]["code"].ToString().Trim() + "' , explanation = '"
                    + dt.Rows[i]["explanation"].ToString().Trim() + "' , gidertipi = "
                    + dt.Rows[i]["gidertipi"].ToString().Trim() + " , vadetarih =  '"
                    + dt.Rows[i]["vadetarih"].ToString().Trim() + "' , pasif = "
                    + dt.Rows[i]["pasif"] + "  where id = "
                    + dt.Rows[i]["id"].ToString().Trim() +
                    " ";

            }

            cmd = new SqlCommand(sqlstr, con);
            cmd.CommandType = CommandType.Text;
            cmd.ExecuteNonQuery();
            con.Close();
        }
    }
}
